[profile.default]
src = "src"
out = "out"
auto_detect_remappings = false
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./broadcast" }, { access = "read", path = "./reports" }]
via_ir = true
optimizer = true

[profile.default.optimizer_details]
# constantOptimizer = true
yul = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
